// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: outward/v1/workspace_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkspaceRegion int32

const (
	WorkspaceRegion_WORKSPACE_REGION_UNSPECIFIED WorkspaceRegion = 0
	WorkspaceRegion_WORKSPACE_REGION_SINGAPORE   WorkspaceRegion = 1
)

// Enum value maps for WorkspaceRegion.
var (
	WorkspaceRegion_name = map[int32]string{
		0: "WORKSPACE_REGION_UNSPECIFIED",
		1: "WORKSPACE_REGION_SINGAPORE",
	}
	WorkspaceRegion_value = map[string]int32{
		"WORKSPACE_REGION_UNSPECIFIED": 0,
		"WORKSPACE_REGION_SINGAPORE":   1,
	}
)

func (x WorkspaceRegion) Enum() *WorkspaceRegion {
	p := new(WorkspaceRegion)
	*p = x
	return p
}

func (x WorkspaceRegion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceRegion) Descriptor() protoreflect.EnumDescriptor {
	return file_outward_v1_workspace_service_proto_enumTypes[0].Descriptor()
}

func (WorkspaceRegion) Type() protoreflect.EnumType {
	return &file_outward_v1_workspace_service_proto_enumTypes[0]
}

func (x WorkspaceRegion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceRegion.Descriptor instead.
func (WorkspaceRegion) EnumDescriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{0}
}

type Workspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region WorkspaceRegion `protobuf:"varint,3,opt,name=region,proto3,enum=outward.v1.WorkspaceRegion" json:"region,omitempty"`
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outward_v1_workspace_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_outward_v1_workspace_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetRegion() WorkspaceRegion {
	if x != nil {
		return x.Region
	}
	return WorkspaceRegion_WORKSPACE_REGION_UNSPECIFIED
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Region WorkspaceRegion `protobuf:"varint,2,opt,name=region,proto3,enum=outward.v1.WorkspaceRegion" json:"region,omitempty"`
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outward_v1_workspace_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outward_v1_workspace_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetRegion() WorkspaceRegion {
	if x != nil {
		return x.Region
	}
	return WorkspaceRegion_WORKSPACE_REGION_UNSPECIFIED
}

type CreateWorkspaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace *Workspace `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
}

func (x *CreateWorkspaceResponse) Reset() {
	*x = CreateWorkspaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outward_v1_workspace_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceResponse) ProtoMessage() {}

func (x *CreateWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outward_v1_workspace_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWorkspaceResponse) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type GetWorkspaceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWorkspaceListRequest) Reset() {
	*x = GetWorkspaceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outward_v1_workspace_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkspaceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceListRequest) ProtoMessage() {}

func (x *GetWorkspaceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_outward_v1_workspace_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceListRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceListRequest) Descriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{3}
}

type GetWorkspaceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspaces []*Workspace `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
}

func (x *GetWorkspaceListResponse) Reset() {
	*x = GetWorkspaceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outward_v1_workspace_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkspaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceListResponse) ProtoMessage() {}

func (x *GetWorkspaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_outward_v1_workspace_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceListResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceListResponse) Descriptor() ([]byte, []int) {
	return file_outward_v1_workspace_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkspaceListResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

var File_outward_v1_workspace_service_proto protoreflect.FileDescriptor

var file_outward_v1_workspace_service_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x22, 0x64, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x09,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x2a, 0x53, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x1c, 0x57, 0x4f,
	0x52, 0x4b, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a,
	0x57, 0x4f, 0x52, 0x4b, 0x53, 0x50, 0x41, 0x43, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x49, 0x4e, 0x47, 0x41, 0x50, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x32, 0xd1, 0x01, 0x0a,
	0x10, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5c, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x75, 0x74, 0x77, 0x61,
	0x72, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6e, 0x76, 0x7a, 0x68, 0x69, 0x2f, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x75, 0x74, 0x77, 0x61, 0x72, 0x64, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outward_v1_workspace_service_proto_rawDescOnce sync.Once
	file_outward_v1_workspace_service_proto_rawDescData = file_outward_v1_workspace_service_proto_rawDesc
)

func file_outward_v1_workspace_service_proto_rawDescGZIP() []byte {
	file_outward_v1_workspace_service_proto_rawDescOnce.Do(func() {
		file_outward_v1_workspace_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_outward_v1_workspace_service_proto_rawDescData)
	})
	return file_outward_v1_workspace_service_proto_rawDescData
}

var file_outward_v1_workspace_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outward_v1_workspace_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_outward_v1_workspace_service_proto_goTypes = []any{
	(WorkspaceRegion)(0),             // 0: outward.v1.WorkspaceRegion
	(*Workspace)(nil),                // 1: outward.v1.Workspace
	(*CreateWorkspaceRequest)(nil),   // 2: outward.v1.CreateWorkspaceRequest
	(*CreateWorkspaceResponse)(nil),  // 3: outward.v1.CreateWorkspaceResponse
	(*GetWorkspaceListRequest)(nil),  // 4: outward.v1.GetWorkspaceListRequest
	(*GetWorkspaceListResponse)(nil), // 5: outward.v1.GetWorkspaceListResponse
}
var file_outward_v1_workspace_service_proto_depIdxs = []int32{
	0, // 0: outward.v1.Workspace.region:type_name -> outward.v1.WorkspaceRegion
	0, // 1: outward.v1.CreateWorkspaceRequest.region:type_name -> outward.v1.WorkspaceRegion
	1, // 2: outward.v1.CreateWorkspaceResponse.workspace:type_name -> outward.v1.Workspace
	1, // 3: outward.v1.GetWorkspaceListResponse.workspaces:type_name -> outward.v1.Workspace
	2, // 4: outward.v1.WorkspaceService.CreateWorkspace:input_type -> outward.v1.CreateWorkspaceRequest
	4, // 5: outward.v1.WorkspaceService.GetWorkspaceList:input_type -> outward.v1.GetWorkspaceListRequest
	3, // 6: outward.v1.WorkspaceService.CreateWorkspace:output_type -> outward.v1.CreateWorkspaceResponse
	5, // 7: outward.v1.WorkspaceService.GetWorkspaceList:output_type -> outward.v1.GetWorkspaceListResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_outward_v1_workspace_service_proto_init() }
func file_outward_v1_workspace_service_proto_init() {
	if File_outward_v1_workspace_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_outward_v1_workspace_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Workspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outward_v1_workspace_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWorkspaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outward_v1_workspace_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWorkspaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outward_v1_workspace_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetWorkspaceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outward_v1_workspace_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetWorkspaceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outward_v1_workspace_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_outward_v1_workspace_service_proto_goTypes,
		DependencyIndexes: file_outward_v1_workspace_service_proto_depIdxs,
		EnumInfos:         file_outward_v1_workspace_service_proto_enumTypes,
		MessageInfos:      file_outward_v1_workspace_service_proto_msgTypes,
	}.Build()
	File_outward_v1_workspace_service_proto = out.File
	file_outward_v1_workspace_service_proto_rawDesc = nil
	file_outward_v1_workspace_service_proto_goTypes = nil
	file_outward_v1_workspace_service_proto_depIdxs = nil
}
