// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file outward/v1/pagination.proto (package outward.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file outward/v1/pagination.proto.
 */
export const file_outward_v1_pagination: GenFile = /*@__PURE__*/
  fileDesc("ChtvdXR3YXJkL3YxL3BhZ2luYXRpb24ucHJvdG8SCm91dHdhcmQudjEiLgoJUGFnZVRva2VuEhEKCXBhZ2Vfc2l6ZRgBIAEoBRIOCgZjdXJzb3IYAiABKANCdgoOY29tLm91dHdhcmQudjFCD1BhZ2luYXRpb25Qcm90b1ABWgpvdXR3YXJkL3YxogIDT1hYqgIKT3V0d2FyZC5WMcoCCk91dHdhcmRcVjHiAhZPdXR3YXJkXFYxXEdQQk1ldGFkYXRh6gILT3V0d2FyZDo6VjFiBnByb3RvMw");

/**
 * @generated from message outward.v1.PageToken
 */
export type PageToken = Message<"outward.v1.PageToken"> & {
  /**
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * @generated from field: int64 cursor = 2;
   */
  cursor: bigint;
};

/**
 * Describes the message outward.v1.PageToken.
 * Use `create(PageTokenSchema)` to create a new message.
 */
export const PageTokenSchema: GenMessage<PageToken> = /*@__PURE__*/
  messageDesc(file_outward_v1_pagination, 0);

