// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file outward/v1/user_service.proto (package outward.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, CreateWorkspaceMemberRequest, CreateWorkspaceMemberResponse, GetUserListRequest, GetUserListResponse, LoginRequest, LoginResponse, LogoutRequest, LogoutResponse } from "./user_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service outward.v1.UserService
 */
export const UserService = {
  typeName: "outward.v1.UserService",
  methods: {
    /**
     * @generated from rpc outward.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc outward.v1.UserService.GetUserList
     */
    getUserList: {
      name: "GetUserList",
      I: GetUserListRequest,
      O: GetUserListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc outward.v1.UserService.CreateWorkspaceMember
     */
    createWorkspaceMember: {
      name: "CreateWorkspaceMember",
      I: CreateWorkspaceMemberRequest,
      O: CreateWorkspaceMemberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc outward.v1.UserService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc outward.v1.UserService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

