// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"

	"github.com/invzhi/outward/internal/id"
)

type CheckIn struct {
	ID           id.ID
	WorkspaceID  id.ID
	CreatedAt    time.Time
	SlackChannel string
	Question     string
	Schedule     []byte
}

type CheckInAnswer struct {
	ID          id.ID
	WorkspaceID id.ID
	CheckInID   id.ID
	UserID      id.ID
	CreatedAt   time.Time
	Answer      string
}

type User struct {
	ID        id.ID
	CreatedAt time.Time
	SlackID   string
}

type Workspace struct {
	ID        id.ID
	CreatedAt time.Time
	SlackID   string
}

type WorkspaceMember struct {
	WorkspaceID id.ID
	UserID      id.ID
}
