// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailContent struct {
	ID        int64
	ProjectID int64
	CreatedAt time.Time
	Payload   string
}

type EmailLayout struct {
	ID        int64
	ProjectID int64
	CreatedAt time.Time
	Payload   string
}

type EmailTemplate struct {
	ID        int64
	ProjectID int64
	CreatedAt time.Time
	Payload   string
}

type EmailTemplateHistory struct {
	ID              int64
	EmailTemplateID int64
	ProjectID       int64
	CreatedAt       time.Time
	Payload         string
}

type Environment struct {
	ID        int64
	ProjectID int64
	CreatedAt time.Time
	Name      string
}

type Project struct {
	ID          int64
	WorkspaceID int64
	CreatedAt   time.Time
	Name        string
}

type ProjectMember struct {
	ProjectID int64
	UserID    int64
	Role      string
}

type User struct {
	ID           int64
	CreatedAt    time.Time
	Email        string
	FirstName    string
	LastName     string
	PasswordHash pgtype.Text
}

type Workspace struct {
	ID        int64
	CreatedAt time.Time
	Name      string
	Region    int32
}

type WorkspaceMember struct {
	WorkspaceID int64
	UserID      int64
	Role        int32
}
