// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/invzhi/outward/internal/id"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailContent struct {
	ID        id.ID
	ProjectID id.ID
	CreatedAt time.Time
	Payload   string
}

type EmailLayout struct {
	ID        id.ID
	ProjectID id.ID
	CreatedAt time.Time
	Payload   string
}

type EmailTemplate struct {
	ID        id.ID
	ProjectID id.ID
	CreatedAt time.Time
	Payload   string
}

type EmailTemplateHistory struct {
	ID              id.ID
	EmailTemplateID id.ID
	ProjectID       id.ID
	CreatedAt       time.Time
	Payload         string
}

type Environment struct {
	ID        id.ID
	ProjectID id.ID
	CreatedAt time.Time
	Name      string
}

type Project struct {
	ID          id.ID
	WorkspaceID id.ID
	CreatedAt   time.Time
	Name        string
}

type ProjectMember struct {
	ProjectID id.ID
	UserID    id.ID
	Role      string
}

type User struct {
	ID        id.ID
	CreatedAt time.Time
	Email     string
	FirstName string
	LastName  string
	Password  pgtype.Text
}

type Workspace struct {
	ID        id.ID
	CreatedAt time.Time
	Name      string
	Region    string
}

type WorkspaceMember struct {
	WorkspaceID id.ID
	UserID      id.ID
	Role        string
}
